### PR TITLE
room bound heaters should have their target temperature set according…

### PR DESCRIPTION
**Pull request by rymsha**
… to current room mode.

### CODE REVIEW

**Comment by Danielhiversen** [comment]
I do not think this is a good idea.
A heater connected to a room, can still be controlled individually.

**Comment by Danielhiversen** [comment]
Currently I think independent_device=False if "Control device individually" is switched on ?

**Comment by rymsha** [comment]
"Control device individually" appeared to be not exactly independent because getIndependentDevices does not return them. So I redone the logic to support 3 modes (I know of).

**Comment by Danielhiversen** [comment]
Awesome, Thanks.

**Pull request merged**
